### PR TITLE
Add CDC/Streaming information to rsources

### LINKED ISSUE #176: TERRA-83 ⁃ Fix docs for CDC/Streaming
Some of the docs show incorrect descriptions, likely from copy-pasting. Example:
https://registry.terraform.io/providers/datastax/astra/latest/docs/resources/cdc

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-83) by [Unito](https://www.unito.io)
┆friendlyId: TERRA-83
┆priority: Major

### PR DESCRIPTION
**Pull request by emerkle826**
Fixes #176 #179 and #180

### CODE REVIEW

**Comment by oscar-b** [comment]
@emerkle826 Hey Erik! Any idea when this will be merged?

**Comment by emerkle826** [comment]
@oscar-b I'll merge this now and release here shortly. Please let me know if it does not satisfy the needs for #180.

**Comment by oscar-b** [comment]
@emerkle826 Awesome! It seems to work nicely, however on subsequent runs I get this from `terraform apply`

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # module.test-project.module.astra-streaming.astra_streaming_tenant.main has changed
  ~ resource "astra_streaming_tenant" "main" {
        id                         = "aaa-test-43472"
      ~ pulsar_token               = (sensitive value)
        # (10 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

**Comment by emerkle826** [comment]
@oscar-b Hmm, yeah. So the token changes every time you call the DevOps endpoint to get the tenant. I need to investigate this to see the best way to handle this. From the terrafrom side, I can ignore the token changes, but that may cause things to break if the previous token is no longer valid after a call to the DevOps API to fetch the tenant, but I don't know that as of yet. I'll create a new ticket with this info.

**Comment by emerkle826** [comment]
Opened #188 for this

**Pull request merged**
