### PR TITLE
Get rid of internal folder to integrate with pulumi

### PR DESCRIPTION
**Pull request by vavsab**
Hi team. I'm trying to wrap your tf package with [Pulumi](https://www.pulumi.com/).
I'm creating a pulumi wrapper myself by following [this big manual](https://github.com/pulumi/pulumi-tf-provider-boilerplate#terraform-bridge-provider-boilerplate). To do this I need to import your package and use all types in it.
I already did it inside of my fork. It works correctly. But at the end I wish to switch to the original package.

If you think that convertion of internal into public is bad please take a look at the official Cloudflare terraform package. [It does not use internal](https://github.com/cloudflare/terraform-provider-cloudflare/tree/master/cloudflare).

Feel free to contact me in Teams if need to discuss this change.

### CODE REVIEW

**Comment by emerkle826** [comment]
Sorry I haven't responded sooner. @vavsab we can accept this contribution as long as you sign our CLA here:
https://cla.datastax.com/

**Comment by vavsab** [comment]
@emerkle826 @phact Please let me know when you are going to approve this. 
It starts to take my time to continiously resolve conflicts.

**Comment by emerkle826** [comment]
@vavsab Would you mind if I take your contribution and update it to the latest? If that is ok, I will get it changed over by Monday.

**Comment by phact** [comment]
Closing because this got done in https://github.com/datastax/terraform-provider-astra/pull/117

**Comment by emerkle826** [comment]
@vavsab I just went ahead and merged an update of this PR in #117. Do you need an official release, or is just having the change committed to the main branch sufficient?

**Comment by vavsab** [comment]
@emerkle826 Thanks for the merge!
I need the official release to have binaries generated. Pulumi will download them to proxy its calls to them.

**Comment by emerkle826** [comment]
@vavsab I just tagged `v2.1.0-rc2`. It should be live in a few minutes. Sorry for the delays.

**Comment by vavsab** [comment]
@emerkle826 Thanks a lot! Finally I [migrated](https://github.com/mapped/pulumi-astra/commit/7a991f13b51ced45428f53dc0a53dbf79e450bdd) to original datastax tf package. Now pulumi provider uses it.

**Pull request closed without merging**
